### ISSUE TITLE
Possibility to expose metrics in Dynamic Extensions bundles

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/alfred-telemetry#122]
[Dynamic Extensions for Alfresco](https://github.com/xenit-eu/dynamic-extensions-for-alfresco) integrates an OSGI container into Alfresco. Extensions build on top of this framework have their own Spring context, which is a child of the main Alfresco context. Furthermore DE bundles can be hot-deployed.

In Alfred Telemetry, the `MeterBinderRegistrar` bean scans the Spring context for relevant beans and registers them. (E.g. `MeterBinder` implementations.) Since Alfred Telemetry scans the main Alfresco context, any beans in the Dynamic Extensions extension won't be processed. Therefore the "auto-configure" functionalities of Alfred Telemetry won't be available for Dynamic Extension bundles.
Furthermore, the hot-deploy functionality is a concern as well. What happens to meter references if a bundle is re-deployed? 

Side note: what is possible in DE bundles at this point, is injecting the `MeterRegistry` to register and maintain metrics manually. 

Is it possible to improve support to expose metrics in Dynamic Extensions bundles?

**Comment by todorinskiz** [comment]
Not in demand, not needed for the moment.
