### ISSUE TITLE
alfred-telemetry-platform declares transitive dependency on Alfresco enterprise

### ISSUE THREAD

**Issue by maoo** [xenit-eu/alfred-telemetry#59]
Hi,

I'd like to use alfred-telemetry, it looks really interesting, thanks for sharing it! I followed the README, but I'm having troubles locating the AMP files; [the link to Maven Central](https://search.maven.org/search?q=g:eu.xenit.alfred.telemetry%20AND%20a:alfred-telemetry-platform) only contain the POM files.

Thanks in advance!

**Comment by kerkhofsd** [comment]
Hi @maoo , 

The AMP file is available in Maven Central. It looks to me like the Maven Central Repository browser does not do a great job in visualizing the fact that there are different artifacts available. 

You can find all artifacts of the last version here:
https://repo1.maven.org/maven2/eu/xenit/alfred/telemetry/alfred-telemetry-platform/0.3.1/

Or you can download the AMP file directly from here:
https://repo1.maven.org/maven2/eu/xenit/alfred/telemetry/alfred-telemetry-platform/0.3.1/alfred-telemetry-platform-0.3.1.amp

Kind regards,
Daan

**Comment by maoo** [comment]
Thanks for the quick response @kerkhofsd !

I still have issues defining it as a dependency; I managed to isolate the issue: if I run `mvn package` on the pom.xml below, I get an error. Do you also have the same issue?

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>sample</artifactId>
    <groupId>com.acme</groupId>
    <version>0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>eu.xenit.alfred.telemetry</groupId>
            <artifactId>alfred-telemetry-platform</artifactId>
            <version>0.3.1</version>
            <type>amp</type>
        </dependency>        
    </dependencies>
</project>
```

Error below:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.acme:sample >---------------------------
[INFO] Building sample 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.350 s
[INFO] Finished at: 2020-12-25T05:06:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sample: Could not resolve dependencies for project com.acme:sample:jar:0.1-SNAPSHOT: Failed to collect dependencies at eu.xenit.alfred.telemetry:alfred-telemetry-platform:amp:0.3.1: Failed to read artifact descriptor for eu.xenit.alfred.telemetry:alfred-telemetry-platform:amp:0.3.1: Failure to find org.alfresco:acs-packaging:pom:6.1.0.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Seems that it can't find `org.alfresco:acs-packaging:pom:6.1.0.5`, which in fact is not listed on https://mvnrepository.com/artifact/org.alfresco/acs-community-packaging . 

Would be possible to update https://github.com/xenit-eu/alfred-telemetry/blob/master/alfred-telemetry-platform/build.gradle#L25 to `6.1.1` (or better, `6.1.2-ga`) ?

Thanks!

**Comment by kerkhofsd** [comment]
Hi @maoo ,

Thanks for your clarification and sorry for the late response. 

To me it looks incorrect that `alfred-telemetry-platform` exposes a dependency on an enterprise edition of Alfresco. 
The current setup results in a POM with `acs-packaging` as a dependency in the `dependencyManagement` section:
https://repo1.maven.org/maven2/eu/xenit/alfred/telemetry/alfred-telemetry-platform/0.3.1/alfred-telemetry-platform-0.3.1.pom

However with my basic Maven knowledge, I would assume that the `dependencyManagement` declares dependencies which are not really used, but can be used for pinpointing versions of dependencies. 
That means Maven tries to resolve the dependency even though it's not really used anywhere? 

Anyway, we'll need to have a look at this and make sure we don't expose ACS enterprise edition dependencies.

**Comment by maoo** [comment]
Hi @kerkhofsd , thanks for your response!

Sorry, I missed the reference to enterprise, I see the comments now on code which states that Alfred is compiled against enterprise, therefore I suppose it's not going to work for community version. 

Is there any plan to change that? It would be fun to fork the project and try to make it compatible for Community, right? If you're not working on it (and don't see major roadblocks), I'd be happy to spend some cycles on it.

TY

**Comment by tgeens** [comment]
The .amp already works for Alfresco Community, but there is indeed this transitive dependency on alfresco-enterprise, which should not be there.

**Comment by tgeens** [comment]
This is available as a snapshot in sonatype snapshots repo: https://oss.sonatype.org/content/repositories/snapshots/eu/xenit/alfred/telemetry/alfred-telemetry-platform/0.3.2-SNAPSHOT/

@maoo can you confirm the snapshot works for you with Alfresco Community ?

**Comment by maoo** [comment]
Yes, issue fixed, thanks a lot @tgeens !
