### ISSUE TITLE
Missing labels on metrics after restarting alfresco

### ISSUE THREAD

**Issue by hvancamp** [xenit-eu/alfred-telemetry#62]
Happening on Alfred telemetry version 0.1.1

When restarting Alfresco the Alfred telemetry metrics who are being scraped by Prometheus are sometimes missing the default micrometer labels:
- application
- host

I have to restart Alfresco multiple times before the metrics again have the correct labels. 

In the screenshot below you see an example of multiple Alfresco restart and therefore metrics with missing labels (the time serie in green).

![missing-labels-on-alfred-telemetry-metrics](https://user-images.githubusercontent.com/32645349/103913918-61112080-5109-11eb-983e-919450e30f69.png)

**Comment by tgeens** [comment]
That's .... funky .... 😑

Have you checked the /prometheus endpoint manually and verified the tags
are not there ?

Kind regards,

Toon Geens

XeniT Solutions NV - http://www.xenit.eu
Diestsevest 32, 4A
B3000 Leuven
+32 16 891 801

**Comment by hvancamp** [comment]
Yes, I checked. They are also missing from the prometheus metrics endpoint on Alfresco. See screenshot below.

![missing-labels-on-alfred-telemetry-metrics-2](https://user-images.githubusercontent.com/32645349/103915534-a0407100-510b-11eb-83a4-eaaa76a7be83.png)

**Comment by tgeens** [comment]
Thanks for checking.

@kerkhofsd any clue ?

**Comment by kerkhofsd** [comment]
Which version of Alfresco? Or more specifically: is this a version of Alfresco which includes Micrometer out of the box? (Alfresco Enterprise >= 6.1)

**Comment by kerkhofsd** [comment]
**If we assume that this is on a version of Alfresco that includes Micrometer out of the box**, this might be an explanation:

- Alfresco's `PrometheusMeterRegistry` is added to the static global composite registry (`Metrics.globalRegistry`). On this `MeterRegistry` no `MeterFilter`s are applied (we don't touch Alfresco's registry).
- Alfred Telemetries `PrometheusMeterRegistry` is added to the static global composite registry. On this `MeterRegistry` the `MeterFilter`s (and hence the common tags) are applied. 
- As we can see [here](https://github.com/xenit-eu/alfred-telemetry/blob/58f8fe3a40a99a1de6b96154ea69b6cfbd3d15d0/alfred-telemetry-platform/src/main/java/eu/xenit/alfred/telemetry/util/PrometheusRegistryUtil.java#L34) the scrape takes the first `PrometheusMeterRegistry` found in the global registry. This might be the Alfresco (no common tags) or the AT (with common tags) one, based on the position of the stars. 

Just a theory that might explain the behavior: to be verified.

**Comment by hvancamp** [comment]
It's an Alfresco v6.1.1 so it indeed includes micrometer out of the box.

With the following metrics properties in alfresco-global.properties:
  - metrics.enabled=true
  - alfred.telemetry.alfresco-integration.enabled=true
  - alfred.telemetry.binder.cache.enabled=true

**Comment by hvancamp** [comment]
Your theory is correct! 

The issue is solved by adding `alfred.telemetry.alfresco-integration.include-default-alfresco-registry=false` 

Maybe this should be the default setting?

**Comment by kerkhofsd** [comment]
@hvancamp thanks for the confirmation. 

Yes, it might be a good idea to disable this by default. 

However disabling the Alfresco `PrometheusMeterRegistry` is only a workaround. We should make sure that we always scrape the Alfred Telemetry `PrometheusMeterRegistry` for our Prometheus endpoint.

**Comment by kerkhofsd** [comment]
After having another look, I think the best approach is indeed disabling the integration of Alfresco's `PrometheusMeterRegistry` by default. 

Furthermore, I think we should add the restriction that only a single `PrometheusMeterRegistry` can be available in the global registry. This means users have two options:

1. Use the Alfresco `PrometheusMeterRegistry` by Alfresco.
    - Both scrape endpoints (`/alfresco/s/alfred/telemetry/prometheus` and `/alfresco/s/prometheus`) will be available
    - Both endpoints contain metrics registered by Alfresco and Alfred Telemetry
    - Both endpoints won't contain any common tags or other `MeterFilter`s. (We don't customize the Alfresco registry)
 
2. Use the `PrometheusMeterRegistry` provided and initialized by Alfred Telemetry
    - Both scrape endpoints will be available
    - The Alfresco endpoint will contain only the metrics registered by Alfresco
    - The Alfresco endpoint won't contain any common tags or other `MeterFilter`s.
    - The AT endpoint will contain metrics registered by Alfresco and Alfred Telemetry. (At least if `alfred.telemetry.alfresco-integration.enabled=true`)
    - The AT endpoint will contain common tags or other `MeterFilter's`

That sounds acceptable, right @tgeens ? 

Maybe we should rename `alfred.telemetry.alfresco-integration.include-default-alfresco-registry` to e.g. `... .alfresco-integration.use-default-alfresco-registry`?

**Comment by tgeens** [comment]
(2) sounds very reasonable
