### ISSUE TITLE
Sharding metrics

### ISSUE THREAD

**Issue by anghelutar** [xenit-eu/alfred-telemetry#85]
Currently sharding metrics are enabled by default. This is not the case in most setups and - depending on configuration - Alfresco's logs might be polluted with errors.

```Caused by: java.lang.NoSuchMethodError: 'java.util.HashMap org.alfresco.repo.index.shard.ShardRegistry.getFlocs()'```

Proposal: by default have the sharding metrics disabled:

alfred.telemetry.binder.solr.sharding.cronexpression=0/10 * * * * ? 2099
alfred.telemetry.binder.solr.sharding.enabled=false
alfred.telemetry.binder.solr.sharding.floc.id.enabled=false

**Comment by kerkhofsd** [comment]
If I'm not mistaking, that `NoSuchMethodError` was fixed [here](https://github.com/xenit-eu/alfred-telemetry/pull/71/files#diff-ff505c374611ab7ae9bcd748024ed68c8085d16096ef78f1f71b9927da8bd7b8R21)? 

Does that mean Alfresco injects another, different `ShardRegistry` in case sharding is not enabled / supported? That sounds very unlikely to me?

**Comment by anghelutar** [comment]
For me simply calling ./gradlew -Penterprise integration-tests:alfresco-enterprise-62:cU triggers that error.

**Comment by kerkhofsd** [comment]
The fix mentioned before was insufficient. 

`Map<Floc, HashMap<Shard, HashSet<ShardState>>>` still doesn't match the `Map<Floc, Map<Shard, Set<ShardState>>>` return type.

**Comment by kerkhofsd** [comment]
Fixed by #86
