### ISSUE TITLE
AEE multiple versions of Micrometer on the classpath can cause troubles

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/alfred-telemetry#96]
[Relates to #20]

AS-IS:
- Alfred Telemetry ships with e specific version of Micrometer (1.0.6 at the moment of this writing)
- Alfresco **Enterprise** Edition >= 6.1 includes a version of Micrometer as well

If there are incompatible changes between those two Micrometer versions, this might cause issues. 

* A specific example:  when starting AEE 6.2.2 with Alfred Telemetry 0.5.0 installed, we observer following error:

    ```
    Caused by: java.lang.NoSuchMethodError: 'io.micrometer.core.instrument.MeterRegistry$Config 
    io.micrometer.core.instrument.MeterRegistry$Config.onMeterRemoved(java.util.function.Consumer)'
    ```

    In this particular case, the out of box Alfresco metrics fail to start because of an incompatibility with the Micrometer version 
    that is actually used in the classpath. In this particular example we can disable Alfresco out of the box metrics as a 
    workaround (`metrics.enabled=false`). Please note that Alfred Telemetry metrics will still be initialized and available. 

* Another example is #20. 
    In that case, Alfred Telemetry failed to start because we were using Micrometer API that was removed in the version shipped with Alfresco. We worked around the problem by refactoring / removing usage of the missing Micrometer API.

To conclude, the main problem here is that the behavior of the out of box Alfresco (enterprise) metrics and Alfred Telemetry is nondeterministic since it might depend on the Micrometer version that is actually used by the classloader. As long as both Alfresco and Alfred Telemetry put different versions on the classpath, there might be incompatibilities and problems in either Alfresco OOTB metrics or Alfred Telemetry metrics.

**Comment by tgeens** [comment]
Proposal:
stop embedding micrometer library, consider the dependency as "provided" - support for Alfresco 6.0(& 6.1) can be dropped, for Aflresco 5.2 there are "additional installation instructions: add micrometer dependency yourself" ?

**Comment by kerkhofsd** [comment]
@tgeens 

Great suggestion! Small remark:
The _"additional installation instructions: add micrometer dependency yourself"_ instruction also applies to **all ACE** version in that case.

**Comment by todorinskiz** [comment]
@kerkhofsd in that train of thought, maybe prepare a separate ready-to-deploy module to make it easier to get started?

**Comment by tgeens** [comment]
To make an analogy: spring boot makes use of publishing `-starter` packages. Those are packages that don't contain any code, but are used to collect a few dependencies transitively.

How could we apply that to `alfred-telemetry` ? 
1. we publish a barebones `alfred-telemetry` package
2. we publish a bunch of `alfred-telemetry-starter-alfresco-community-XX` packages ?

Those starters just put a dependency on `alfred-telemetry` + a micrometer version (if you need one) + maybe some default registries ?

(Or instead of those very long artifact names, we could consider using the classifier in the maven coordinates for this purpose ?)

**Comment by kerkhofsd** [comment]
@tgeens @thijslemmens @todorinskiz 

A try to summarize all the options I've heard so far:

(ACSEE = Alfresco Content Services Enterprise Edition, ACSCE = Alfresco Content Services Community Edition)

* Don't ship Micrometer jars by default, introduce `alfred-telemetry-starter-...` packages
    *  ACSEE >= 6.1: jars are shipped by Alfresco, no need to add them. However, I think we'll still need to add `micrometer-extras` in that case. 
    * ACSEE < 6.1 or ACSCE: `alfred-telemetry-starter-...` should be added 
* Don't ship Micrometer jars by default, document that these should be added for ACSEE < 6.1 and ACSCE.
* Introduce empty overwrites for Alfresco Micrometer jars
    * Alfred Telemetry ships with a specific Micrometer version (e.g. 1.3.5)
    * For older Micrometer versions that ship with Alfresco (e.g. 1.0.6 for ACSEE 6.1), we ship an empty `micrometer-core-1.0.6.jar` which will overwrite the Alfresco jar. 
    * Only one set of classfiles available on the classpath

I think we should start making a decision here?

**Comment by todorinskiz** [comment]
cc @tgeens @thijslemmens wdyt?

**Comment by tgeens** [comment]
Option 1 = Option 2 + new `-starter` modules to make gathering the dependencies easier ?

I'd vote for Option 1

**Comment by kerkhofsd** [comment]
Just for completeness, there is an option 4:

- don't change anything and observe and fix issues when they occur. (As we did for the two issues mentioned in the original comment). 

For option 1. and 2. we still need to be compatible with all Micrometer versions shipped with different AEE editions. That might sooner or later too.
